name = "artigos"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[env.production]
routes = [
  { pattern = "artigos.pages.dev", zone_name = "pages.dev" }
]

[build]
command = "npm run build"
cwd = ""
watch_paths = []

[[env.production.routes]]
pattern = "artigos.pages.dev/*"
zone_name = "pages.dev"
custom_domain = true
